Mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('photo/',include('photo.urls')),
    path('auth/', include('users.urls')),
    path('QnA/', include('QnA.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QnA/urls.py
from django.urls import path
from . import views
# from .views import *

app_name="QnA"

urlpatterns = [
    path("QnA/<int:photo_pk>/question/", views.question_view, name='question_view'),
    path('QnA/<int:question_pk>/answer/', views.answer_view, name="answer_view"),
]

photo/urls.py
from django.urls import path
from .views import *
from . import views

app_name='photo'

urlpatterns = [
    path('upload/', PhotoUploadView.as_view() , name="photo_upload"), 
    path('photo/', views.photo_view, name="photo_view"),
    path('photo/<int:pk>/', views.photo_detail, name="photo_detail"),
]

users/urls.py
from django.urls import path
from . import views

app_name="user"

urlpatterns = [
    path("login", views.login_view, name='login'),
    path("logout", views.logout_view, name="logout"),   
    path("signup", views.signup_view, name="signup")
]

QnA/models.py
from django.db import models
# from django.core.validators import MinLengthValidator

from photo.models import Photo

# Create your models here.


class Question(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name='photo_questions') # 1:n (사진 1개 : 여러개 질문 n) 사진이 삭제되면 질문을 전부 지우겠음 CASCADE
    question = models.CharField(max_length=500)
   

class Answer(models.Model):
    question = models.OneToOneField(Question, on_delete=models.CASCADE) # 1:1 (질문 1개 : 답변 1개)    질문이 삭제되면 답변을 전부 지우겠음 
    answer = models.CharField(max_length=500)
    
    
    
    

photo/models.py
from django.db import models

# Create your models here.

# 1. 모델 : 데이터베이스 저장될 데이터가 있다면 해당 데이터를 묘사한다.
# 2. 뷰(기능) : 계산, 처리 - 실제 기능, 화면
# 3. URL 맵핑 : 라우팅 테이블에 기록한다. urls.py에 기록 - 주소를 지정
# 4. 화면에 보여줄 것이있다 : 템플릿작성(html)

# 장고의 기본 유저 모델
# from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.deletion import CASCADE
from django.db.models.fields import IntegerField
from django.urls import reverse

# settings.AUTH_USER_MODEL

# 외래키(ForeignKey) - User 테이블에서 해당 유저를 찾을 수 있는 주키
# 주키(PrimaryKey) - User 테이블에 1 admin x x x x
# User테이블에서 그 유저가 쓴 포토를 어떻게 불러올 것인지

class Photo(models.Model): # 기본적으로 id가 생성되고 id는 primarykey값을 가짐
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='user_photos') 
    photo = models.ImageField(upload_to="photos/%y/%m/%d")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse("photo:photo_detail", args=[self.id])
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    student_id = models.CharField(max_length=10)
    

QnA/forms.py
from django import forms 
from .models import Question, Answer

class questionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question']
        

class answerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['answer']
        

QnA/views.py
from django.db.models import fields
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Question, Answer, Photo
from django.contrib.auth.decorators import login_required
from django import forms
from . import models
from .forms import questionForm, answerForm

# from django.contrib.auth.decorators import login_required
# Create your views here.

# @login_required

# 사진 번호에 맞게 질문이 저장되어야 함

@login_required
def question_view(request, photo_pk):
    photo = get_object_or_404(Photo, pk=photo_pk)
    if request.method=='POST':
        form = questionForm(request.POST, request.FILES)
        if form.is_valid():
            qst = form.save(commit=False)
            qst.photo = photo
            qst.author = request.user
            qst.save()
            return redirect('QnA:answer_view', qst.pk)
    else:
        form = questionForm()
    return render(request, "QnA/question.html", {'form':form})


@login_required
def answer_view(request, question_pk):
    question= get_object_or_404(Question, pk=question_pk)
    if request.method=="POST":
        form = answerForm(request.POST, request.FILES)
        if form.is_valid():
            ans = form.save(commit=False)
            ans.question=question
            ans.author = request.user
            ans.save()
            return redirect('photo:photo_view')
    else:
        form = answerForm()
    return render(request, "QnA/answer.html", {'form':form})

photo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Photo
from django import forms
# Create your views here.

from django.views.generic.edit import CreateView

class PhotoUploadView(CreateView): 
    model = Photo # 제네릭뷰같은 경우엔 무조건 model이 필요하다
    # 어떤 내용들을 입력받을거냐
    fields=['photo'] 
    template_name="photo/upload.html"

    def form_valid(self, form): 
        form.instance.author_id = self.request.user.id
        if form.is_valid(): # 입력한 데이터가 다 올바르면
            form.instance.save()
            return redirect('photo:photo_view') 
        else:
            return self.render_to_response({'form':form})

def photo_view(request):
    photo_list = Photo.objects.all()
    return render(request, 'photo/photo.html', {'photo_list':photo_list})

def photo_detail(request, pk):
    photo=get_object_or_404(Photo, pk=pk)
    return render(request, 'photo/detail.html', {'photo':photo})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User
# Create your views here.

def login_view(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            print("인증성공")
        else:
            print("인증실패")

    return render(request,"users/login.html")

def logout_view(request):
    logout(request)
    return redirect("user:login")

def signup_view(request):
    if request.method=="POST":
        print(request.POST)
        username=request.POST["username"]
        password=request.POST["password"]
        firstname=request.POST["firstname"]
        lastname=request.POST["lastname"]
        email=request.POST["email"]
        student_id=request.POST["student_id"]

        user = User.objects.create_user(username, email, password)
        user.last_name = lastname
        user.first_name = firstname
        user.student_id =student_id
        user.save()
        return redirect("user:login")

    return render(request, "users/signup.html")

QnA/templates/QnA/answer.html
<form action="" method="POST">
    {% csrf_token %}
    <p>답변입력</p>
    <input name="answer" type="text">
    <input value="sign up" type="submit">
</form>

QnA/templates/QnA/question.html
<form action="" method="POST">
    {% csrf_token %}
    <p>질문입력<p>
    <input name="question" type="text">
    <input value="sign up" type="submit">
</form>

photo/templates/photo/detail.html
{% extends "photo/layout.html" %}
<html>
<head>
    <meta charset="utf-8"/>
    {% block extra_head %}
    <style>
        .post_photo{
            max-width: 40%;
        }
    </style>
    {% endblock %}
</head>
<body>
    {% block photo %}
        {% if photo.photo %}
            <img src="{{ photo.photo.url }}" class="post_photo" />
        {% endif %}
    <br>

    <div class="panel-footer">
        <a href="{% url "photo:photo_view" %}">목록으로</a>
        <a href="{% url "QnA:question_view" photo.pk %}">질문입력</a>
    </div>
    {% endblock %}

</body>
</html>

photo/templates/photo/layout.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
    <h1>photo</h1>
    {% block extra_head %} {% endblock %}
</head>
<body>
    {% block photo %}
    {% endblock %}
    <table>
    </table>
</body>
</html>

photo/templates/photo/photo.html
{% extends "photo/layout.html" %}
{% block photo %}
    <ul>
    <a href="{% url 'user:login' %}">로그인</a>
    <a href="{% url 'photo:photo_upload' %}">사진 업로드</a>
    <br>
    <br>
    {% block extra_head %}
    <style>
        .post_photo{
            max-width: 40%;
        }
    </style>
    {% endblock %}

    {% for photo in photo_list %}
    <li>
        <a href="{% url "photo:photo_detail" photo.pk %}">
            <img src="{{ photo.photo.url }}"  class="post_photo" />
        </a>
    </li>
    {% endfor %}
    </ul>
{% endblock %}

photo/templates/photo/upload.html
사진 업로드
<br>
<form action="" method="post" enctype="multipart/form-data">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" value="Upload">
    <br>
    <br>
    <a href="{% url "photo:photo_view" %}">목록으로</a>
</form>

users/templates/users/login.html
로그인 페이지
<br>

{% if user.is_authenticated %}
    로그인성공
    {{ user.username}}님 환영합니다.
    <a href="{% url 'user:logout' %}">로그아웃</a>
    <br>
    <a href="{% url 'photo:photo_upload' %}">사진 업로드</a>

{% else %}
    <form action="" method="POST">
        {% csrf_token %}
        <input name="username" type="text">
        <input name="password" type="password">
        <input type="submit" value="login">
    </form>
    <a href="{% url 'user:signup' %}">회원가입</a>

{% endif %}

users/templates/users/signup.html
회원가입 페이지
<br>

<form action="" method="POST">
    {% csrf_token %}
    <p>아이디</p>
    <input name="username" type="text">
    <p>비밀번호</p>
    <input name="password" type="password">
    <p>성</p>
    <input name="firstname" type="text">
    <p>이름</p>
    <input name="lastname" type="text">
    <p>이메일</p>
    <input name="email" type="text">
    <p>학번</p>
    <input name="student_id" type="text">
    <input type="submit" value="sign up">
</form>